### PR TITLE
init go.sum

### PR DESCRIPTION
**Pull request by redyapr**
init go.sum to pass golangci-lint typecheck

this error will happen if no go.sum file:
```
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package uniseg: could not load export data: no export data for "github.com/rivo/uniseg"
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: buildir: failed to load package uniseg: could not load export data: no export data for "github.com/rivo/uniseg"
```

### CODE REVIEW

**Comment by redyapr** [comment]
this error will happen if no go.sum file:
```level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package uniseg: could not load export data: no export data for \"github.com/rivo/uniseg\""
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package uniseg: could not load export data: no export data for \"github.com/rivo/uniseg\"\n\n"
make: *** [Makefile:305: lint] Error 3```

**Comment by rivo** [comment]
I merged this although I believe it's a nonsensical error message by the linter.

**Comment by redyapr** [comment]
thanks a lot @rivo for make this happen.
I believe this will help many people that using your library along with linter.
because start from go 1.17 require go.sum file although empty file init

**Comment by redyapr** [comment]
thanks a lot @rivo to make this happen.
I believe this will help many people that using your useful library along with linter.
because start from go 1.17 require go.sum file although empty file init

**Pull request merged**
